// Code generated by "stringer -type=CauseTx"; DO NOT EDIT.

package vv104

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Per_Cyc-1]
	_ = x[Back-2]
	_ = x[Spont-3]
	_ = x[Init-4]
	_ = x[Req-5]
	_ = x[Act-6]
	_ = x[ActCon-7]
	_ = x[Deact-8]
	_ = x[DeactCon-9]
	_ = x[ActTerm-10]
	_ = x[Retrem-11]
	_ = x[Retloc-12]
	_ = x[File-13]
	_ = x[Inrogen-20]
	_ = x[Inro1-21]
	_ = x[Inro2-22]
	_ = x[Inro3-23]
	_ = x[Inro4-24]
	_ = x[Inro5-25]
	_ = x[Inro6-26]
	_ = x[Inro7-27]
	_ = x[Inro8-28]
	_ = x[Inro9-29]
	_ = x[Inro10-30]
	_ = x[Inro11-31]
	_ = x[Inro12-32]
	_ = x[Inro13-33]
	_ = x[Inro14-34]
	_ = x[Inro15-35]
	_ = x[Inro16-36]
	_ = x[Reqcogen-37]
	_ = x[Reqco1-38]
	_ = x[Reqco2-39]
	_ = x[Reqco3-40]
	_ = x[Reqco4-41]
	_ = x[UkTypeId-44]
	_ = x[UkCauseTx-45]
	_ = x[UkComAdrASDU-46]
	_ = x[UkIOA-47]
}

const (
	_CauseTx_name_0 = "Per_CycBackSpontInitReqActActConDeactDeactConActTermRetremRetlocFile"
	_CauseTx_name_1 = "InrogenInro1Inro2Inro3Inro4Inro5Inro6Inro7Inro8Inro9Inro10Inro11Inro12Inro13Inro14Inro15Inro16ReqcogenReqco1Reqco2Reqco3Reqco4"
	_CauseTx_name_2 = "UkTypeIdUkCauseTxUkComAdrASDUUkIOA"
)

var (
	_CauseTx_index_0 = [...]uint8{0, 7, 11, 16, 20, 23, 26, 32, 37, 45, 52, 58, 64, 68}
	_CauseTx_index_1 = [...]uint8{0, 7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 58, 64, 70, 76, 82, 88, 94, 102, 108, 114, 120, 126}
	_CauseTx_index_2 = [...]uint8{0, 8, 17, 29, 34}
)

func (i CauseTx) String() string {
	switch {
	case 1 <= i && i <= 13:
		i -= 1
		return _CauseTx_name_0[_CauseTx_index_0[i]:_CauseTx_index_0[i+1]]
	case 20 <= i && i <= 41:
		i -= 20
		return _CauseTx_name_1[_CauseTx_index_1[i]:_CauseTx_index_1[i+1]]
	case 44 <= i && i <= 47:
		i -= 44
		return _CauseTx_name_2[_CauseTx_index_2[i]:_CauseTx_index_2[i+1]]
	default:
		return "CauseTx(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
