// Code generated by "stringer -type=Qoi"; DO NOT EDIT.

package vv104

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[notUsed-0]
}

const _Qoi_name = "notUsed"

var _Qoi_index = [...]uint8{0, 7}

func (i Qoi) String() string {
	if i >= Qoi(len(_Qoi_index)-1) {
		return "Qoi(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Qoi_name[_Qoi_index[i]:_Qoi_index[i+1]]
}
