// Code generated by "stringer -type=Qu"; DO NOT EDIT.

package vv104

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[noAddDef-0]
	_ = x[shortPulse-1]
	_ = x[longPulse-2]
	_ = x[persistent-3]
}

const _Qu_name = "noAddDefshortPulselongPulsepersistent"

var _Qu_index = [...]uint8{0, 8, 18, 27, 37}

func (i Qu) String() string {
	if i >= Qu(len(_Qu_index)-1) {
		return "Qu(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Qu_name[_Qu_index[i]:_Qu_index[i+1]]
}
